services:
  - type: web
    runtime: static
    name: portfolio-emmanuel
    buildCommand: npm install && npm run build
    staticPublishPath: ./out
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
    routes:
      - type: rewrite
        source: /404
        destination: /404.html
    headers:
      - path: /_next/static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
